# Generated by Django 2.2 on 2019-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='interrogative',
            field=models.CharField(default='what', max_length=2000),
            preserve_default=False,
        ),
    ]
